In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [2]:
Johnson_straddle = pd.read_csv("Johnson_straddle_returns.csv", skiprows=6)

In [3]:
Johnson_straddle.columns = [
    "date",
    "1m",
    "2m",
    "3m",
    "6m",
    "9m",
    "12m",
    "1m-short",
    "2m-short",
    "3m-short",
    "6m-short",
    "9m-short",
    "12m-short",
]
Johnson_straddle.head()

,date,1m,2m,3m,6m,9m,12m,1m-short,2m-short,3m-short,6m-short,9m-short,12m-short
0,19960105,-4.067,0.827,1.018,-0.307,-0.067,0.855,0.500,-0.145,-0.221,0.101,0.029,-0.428
1,19960108,-1.795,-0.642,-0.443,0.307,0.234,0.167,0.224,0.116,0.098,-0.101,-0.101,-0.085
2,19960109,34.233,9.657,4.109,-0.396,-0.324,4.148,-4.098,-1.743,-0.916,0.132,0.141,-2.104
3,19960110,0.968,-2.854,-1.956,0.723,-0.770,-5.758,-0.139,0.597,0.482,-0.246,0.340,3.095
4,19960111,-9.191,-6.238,-3.260,1.116,-1.824,-1.151,1.410,1.363,0.842,-0.404,0.835,0.594

In [4]:
Johnson_straddle["date"] = pd.to_datetime(Johnson_straddle["date"], format="%Y%m%d")
Johnson_straddle.head()

,date,1m,2m,3m,6m,9m,12m,1m-short,2m-short,3m-short,6m-short,9m-short,12m-short
0,1996-01-05,-4.067,0.827,1.018,-0.307,-0.067,0.855,0.500,-0.145,-0.221,0.101,0.029,-0.428
1,1996-01-08,-1.795,-0.642,-0.443,0.307,0.234,0.167,0.224,0.116,0.098,-0.101,-0.101,-0.085
2,1996-01-09,34.233,9.657,4.109,-0.396,-0.324,4.148,-4.098,-1.743,-0.916,0.132,0.141,-2.104
3,1996-01-10,0.968,-2.854,-1.956,0.723,-0.770,-5.758,-0.139,0.597,0.482,-0.246,0.340,3.095
4,1996-01-11,-9.191,-6.238,-3.260,1.116,-1.824,-1.151,1.410,1.363,0.842,-0.404,0.835,0.594

In [5]:
Johnson_straddle.info()

<class 'pandas.DataFrame'>
RangeIndex: 5911 entries, 0 to 5910
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       5911 non-null   datetime64[us]
 1   1m         5911 non-null   float64
 2   2m         5911 non-null   float64
 3   3m         5911 non-null   float64
 4   6m         5911 non-null   float64
 5   9m         5911 non-null   float64
 6   12m        5911 non-null   float64
 7   1m-short   5911 non-null   float64
 8   2m-short   5911 non-null   float64
 9   3m-short   5911 non-null   float64
 10  6m-short   5911 non-null   float64
 11  9m-short   5911 non-null   float64
 12  12m-short  5911 non-null   float64
dtypes: datetime64[us](1), float64(12)
memory usage: 600.5 KB

In [8]:
Johnson_swap = pd.read_csv("Johnson_variance_swap_return.csv", skiprows=5)
Johnson_swap.columns = [
    "date",
    "1m",
    "2m",
    "3m",
    "6m",
    "9m",
    "12m",
]
Johnson_swap["date"] = pd.to_datetime(Johnson_swap["date"], format="%Y%m%d")


Johnson_swap.head()

        date      1m      2m      3m      6m     9m    12m
0 1996-01-05 -11.085  -2.301  -0.602  -0.565  7.678 -2.664
1 1996-01-08 -12.987  -6.969  -3.980  -5.730 -9.234 -1.680
2 1996-01-09  86.430  34.366 -10.423  16.073  7.596  4.283
3 1996-01-10   2.044  17.554  31.737   1.317  2.662  6.638
4 1996-01-11 -18.110 -12.136  -9.380  -5.368 -7.016 -3.465

In [9]:
print(f"johnson straddle 1 month mean: {Johnson_straddle["1m"].mean()}")
print(f"johnson straddle 2 month mean: {Johnson_straddle["3m"].mean()}")
print(f"johnson straddle 3 month mean: {Johnson_straddle["3m"].mean()}")
print(f"johnson straddle 6 month mean: {Johnson_straddle["6m"].mean()}")
print(f"johnson straddle 9 month mean: {Johnson_straddle["9m"].mean()}")
print(f"johnson straddle 12 month mean: {Johnson_straddle["12m"].mean()}")

johnson straddle 1 month mean: -0.3215839959397733
johnson straddle 2 month mean: -0.1040226695990526
johnson straddle 3 month mean: -0.1040226695990526
johnson straddle 6 month mean: -0.0359132126543732
johnson straddle 9 month mean: -0.013873456267974957
johnson straddle 12 month mean: 0.0071250211470140455

In [10]:
print(f"Johnson swap 1 month mean : {Johnson_swap["1m"].mean()}")
print(f"Johnson swap 2 month mean : {Johnson_swap["2m"].mean()}")
print(f"Johnson swap 3 month mean : {Johnson_swap["3m"].mean()}")
print(f"Johnson swap 6 month mean : {Johnson_swap["6m"].mean()}")
print(f"Johnson swap 12 month mean : {Johnson_swap["12m"].mean()}")

Johnson swap 1 month mean : -1.4069123519458546
Johnson swap 2 month mean : -0.7105700507614212
Johnson swap 3 month mean : -0.4226169204737733
Johnson swap 6 month mean : -0.23952927241962774
Johnson swap 12 month mean : -0.09866835871404399